<?php include 'header.php'; ?>



<div class="container container1">
	<div class="well">
	<h1 id="center">Privcay Policy</h1>
</div>

<div class="container">
  <h3><b>Prvacy Policy :</b></h3>
	<p id="justify">We (“Wolotech L.L.P.”, "Wolotech", “Eatsapp”, "Company," "we," "us," and "our,") respect your privacy and we are fully committed to protect it and keeping it safe with us.</p>
      <p id="justify">Reference to “you / your / user / customer / purchaser” in this Privacy Policy refers to the users of this Application / Website whether or not you access the services available on the Application / Website or surf / browse / transaction on the Application / Website. Any person who accesses this Service is presumed to be legally capable of entering into a legal contract and has understood and voluntarily accepted the said Privacy Policies. Any person who accesses the Eatsapp Service is presumed to be legally capable of entering into a legal contract and has understood and voluntarily accepted the Terms of the Privacy Policy.</p>
      <p id="justify">Only individuals who are 18 years of age or older may use the SERVICE. If you are under 18 years of age and you wish to download, install, access or use the SERVICE, your parents or legal guardian must acknowledge and agree to the Terms of Service and Privacy Policy. Should your parents or legal guardian fail to agree or acknowledge the Terms of Service and Privacy Policy, you shall not use our SERVICE and or immediately discontinue its use them immediately.</p>
      <p id="justify">This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000.</p>
      <p id="justify">Privacy Policy governs and describes the types of information that we may collect when you use or access our Application and our website www.Eatsapp.in, www.wolotech.com and our “Eatsapp” application for Mobile and handheld devices (the “App”) and how we will be collecting, using, sharing the collected information.</p>
      <p>The Website and the App are jointly referred to as the “SERVICE”).</p>
      <p id="justify">This policy applies only to information we collect through our SERVICE, via email, via text and via other electronic communications sent through or in connection with our Services. Information communicated to us our third party through telephonic communication is not covered.</p>
      <p id="justify">This policy does not apply to the information you directly or indirectly or accidently or unknowingly share on Social Media and Social Network Sites that you use in connection with our Services. We are not responsible in protecting such information. You are responsible to check with those third party services / sites about their privacy policies and agree with them before using their Services.</p>
      <p id="justify">It is required that you understand each part of this document completely and only once you have understood them fully and are agreeing each and every part hereof, you may use our SERVICE. In case if you do not agree with even a single point, you are advised not to use our SERVICE. It will be construed as acceptance of the said Privacy Policies if you use or access our SERVICE.
</p>
      <p id="justify">We will be updating our Privacy Policies from time to time and it is absolutely your responsibility to keep checking such updates. Your using our services will mean that you have read and understood the latest updated Privacy Policies and are in fully agreement with it. We are not responsible for informing you about informing you about such updates.</p>
      <p id="justify">Personal Information (type 1): These include any information that is personal in nature. Any information that can be used to directly or indirectly identify a particular person is considered as Personal Information. This information includes, but is not limited to name, phone number, email address, addresses with postal code birth date, age, gender, photograph(s), biometrics, phone carrier, food ordering details and history, special restaurant requests, your reviews & feedbacks, date, time and location of placing the order and where you want it to be delivered, your GPS locations, track your route, your searches and selected options, number of clicks, pages viewed and the order of those pages, how long you visited our Services, the date and time you used the Services, error logs, and other similar information, usage details, type of orders, your preferred pitstops, preferred food outlets, your travel destinations your preferred hangout locations, your preferred addresses, your preferred food and beverages, , your preferred routes, communications between you and us by email, information about your computer, Internet connection and mobile device, including your IP address, operating systems, platforms, browser type, other browsing information (connection, speed, connection type etc.), device type, device’s unique device identifier, mobile network information and the device’s telephone number, cookies, online or offline status of your application, presence and or absence and or details pertaining to other applications on your mobile phone.</p>
      <p id="justify">Personal Information (type 2): This information includes but is not limited to all personal information such as billing information, credit card, debit card, e-Wallets details, Bank Details, Bank Account Details, UPI Details and any other details of payment instrument, etc…</p>
      <p id="justify">Delivery Partners: These are our partner entities that will be providing the service of picking up the order from food outlets and deliver it to you. They will require and we will share with them information including but not limited to your name, phone number, addresses, GPS locations, delivery location, photograph, etc…</p>
      <p id="justify">Food Outlets: These are our partner entities that will be providing the service of keeping the order ready to be picked up by our delivery partners. They will maintain the menu and keep it updated to have everything listed on the menu available for orders. These Food Outlets may be individual outlets or chain having several outlets. They will be responsible for quality of food provided to you. We insist but in no way we can ensure that they provide food that is compliant with Food Safety & Standard Act, Package & Label Act and Weight and Measures Act. These partners will require information that will include but not limited to your name, phone number, addresses, GPS locations, delivery location, photograph, your order, order preferences, etc…</p>
      <p id="justify">Payment Partners: These partners include not limited to those who process the payment and complete the transaction, Vendors who provide fraud detection services to us and other third parties. To make payments, we ask for Personal Information (type 2). By submitting your Personal Information (type 2), through our Services, you expressly consent to the sharing of your information with our payment processors or payment gateways, and other third-party service providers (including but not limited to vendors who provide fraud detection services to us and other third parties). These Payment Partners may store your Personal Information (type 2). </p>
      <p id="justify">Third Party: These include Delivery Partners, Food Outlets, Payment Partners and or any person or entity other than you or us.</p>
      <p id="justify">Cookies, Web Beacons, etc: We use cookies collected to Authenticate your login information, Enable our security features, Show you advertising and Improve and develop the features of the Website. In addition to the cookies, we may also collect information to enable us to better understand you so that we can improve your user experience. In an effort to make the Website affective and improve the Website, certain information may be collected each time you access the Website. Such information may be saved in server logs in an encrypted form which may not identify you personally. Such information or data may include, but shall not limit to, IP address, your server details and duration of your visit, date, time or purpose of your visit. In addition to cookies we use web beacons, ad tags, pixels to advertise as part of the Website. The abovementioned data may be used by us and may be shared with our sponsors, investors, advertisers, developers, strategic business partners or other associates to enhance and grow the user experience in relation to the Website.</p>
      <p id="justify">Information Storing and Sharing: We use the information you provide to us to serve you as required. The information is stored and also shares with Third Parties, who may also share or store them. The information will also be used to provide and or improve the quality of our SERVICE, and may be to personalize our SERVICE for you. We also use this information to communicate with you, and comply with our legal obligations.</p>
      <p id="justify">For registration we only ask for your name and mobile number. You are at your own liberty to fill in the additional details under profile. This is not mandatory and you will still be able to get equally satisfactory SERVICE even if you choose not to fill in additional information in the Profile page. Other details will be required for successful deliveries such as addresses, location detail including but not limited to GPS, tracking and sharing your location etc…</p>
      <p id="justify">Other information that we collect which you do not personally fill in include various parts of Personal Information (Type 1) and Personal Information (type 2). This information is required to serve you and give you better user experience.</p>
      <p id="justify">Personal Information (type 2) are not stored on our servers. Once you fill in the details, they are transferred to the Payment Partners and immediately removed from our servers.</p>
      <p id="justify">In case we are required to respond to or required to disclose your personal information in order to assist the Government Authority or in adherence to the Court Order or other legal process or to protect the interest of our Service and / or any particular user(s), we will disclose it without obtaining permission from you. You authorize us to disclose your personal information. This may include Personal Information (type 1) and also Personal Information (type 2).</p>
      <p id="justify"><b>Communication:</b> We will pass on the information to you via Notifications in the Mobile Application. We may also communicate on email if you have provided it to us. We plan to email the Bills on every successful placing of order, which will happen only on email. We will not be sending the Bills on your address even if we have your Registered and other address(es). We will store history of notifications sent to you temporarily or  permanently or delete them without any intimation to you. We may also communicate on SMS, MMS or phone calls or other forms of communication to share information with you. We may also send advertisements via any of the above communication methods and or send promotional materials of our or our affiliates, subsidiaries, business partners, advertisers and sponsors. You may receive such communication when you have registered as a user.</p>
      <p id="justify"><b>Legal:</b> Terms and your use of our Service is governed by, construed and enforced in accordance with the laws of India applicable to contracts made, executed and wholly performed on the our SERVICE, and, for the purposes of any and all legal or equitable actions then you and us shall be referred to arbitration in accordance with the provisions of the arbitration law in city of Mumbai only. And if for any reason whatsoever, arbitration judgment is not satisfactory either you or us agree and submit to the exclusive jurisdiction and venue of the Courts of Mumbai and you will not object to such jurisdiction or venue.</p>
      <p id="justify">Security: We strive to ensure the security, integrity and privacy of your Personal Information and protect it against any unauthorized access or unauthorized alteration, disclosure or destruction. It should be clearly understood that we are not responsible for any breach of security or for any actions of any entity that receive your Personal Information. User understands, acknowledges and agrees that although we provide appropriate protection, the Internet and hence our SERVICE is not hack proof. Data pilferage due to unauthorized hacking, virus attacks, technical issues is possible and we are not responsible for any outcomes of such event(s). If we receive any orders, or any sort of communication, requests, from your mobile number or your email address, we will consider that it is you who have communicated and we will have no reason to think otherwise. We do not provide any security for opening the application. You are required to keep your mobile device and your email access secure.</p>
      <p id="justify">Indemnification: You agree and confirm to indemnify, defend and hold us, our parents, subsidiaries, affiliates, successors, assigns and licensors, franchisees or sub-franchisees, any of our respective officers, founders, owners, partners, directors, employees, agents, vendors, licensors, representatives, advertisers, service providers and suppliers harmless from and against any and all claims, actions, losses, expenses, damages and costs (including reasonable attorneys' fees), resulting from any breach including but not limited to Security or violation of Terms, or due to your activities related to the SERVICE, whether by use of your account or otherwise or due to Events beyond our control.</p>
      <p id="justify">Your data may get damaged, lost, pilfered, garbled or become useless. You understand, acknowledge and agree that you are assuming the entire risk of all Personal Information (type 1) and Personal Information (type 2), its safety and security when you use our SERVICE. You understand and agree to the fullest extent permissible by the law, we, our funders, our office bearers, our staff and employees and our successors and assigns, Delivery Partners, Food Outlets, Payment Partners or any of their affiliates, or their respective officers, founders, owners, partners, directors, employees agents licensors, representatives, operational service providers, advertisers, or suppliers, shall not be liable for any loss or damage of any kind, direct or indirect, in connection with or arising from use of our SERVICE from these terms including but not limited to compensatory, consequential, incidental, indirect, special or punitive damages.</p>
      <p id="justify">UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER IN TORT, CONTRACT, OR OTHERWISE, SHALL WE BE LIABLE TO YOU OR TO ANY OTHER PERSON OR ENTITY FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF GOODWILL, LOSS OF CONFIDENTIAL OR OTHER INFORMATION, BUSINESS INTERRUPTION, WORK STOPPAGE, MOBILE AND OR COMPUTER FAILURE OR MALFUNCTION, PERSONAL INJURY, HEALTH, LOSS OF PRIVACY, FAILURE TO MEET ANY DUTY INCLUDING A DUTY OF GOOD FAITH OR OF REASONABLE CARE, NEGLIGENCE (WHETHER ACTIVE OR PASSIVE), AND ANY OTHER PECUNIARY OR OTHER LOSS WHATSOEVER) ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OR INABILITY TO USE THE SERVICE, LOSS OF DATA OR OTHERWISE UNDER OR IN CONNECTION WITH ANY PROVISION OF THESE TERMS, EVEN IN THE EVENT OF FAULT, TORT (INCLUDING NEGLIGENCE AND GROSS NEGLIGENCE), STRICT LIABILITY, BREACH OF CONTRACT, OR BREACH OF WARRANTY, AND EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL WE BE LIABLE FOR ANY DAMAGES IN EXCESS OF YOUR LAST ORDER PLACED ON EATSAPP APP IF ANY.</p>
      <p id="justify">Queries: In case of any queries, please write to Wolotech LLP on registers address (Wolotech LLP, 152, 15th Floor, Mittal Court (B), Nariman Point, Mumbai 400021) or send an email on contact@wolotech.com with subject “Grievance – Mobile Number”.</p>
</div></div>

<?php include 'footer.php'; ?>