<?php include 'header.php'; ?>



<div class="container container1">
	<div class="well">
	<h1 id="center">Terms of Service</h1>
</div>
<div class="container">
    <h3><b>Terms of Service :</b></h3>
	<p id="justify">We (“Wolotech L.L.P.”, "Wolotech", “Eatsapp”, "Company," "we," "us," and "our,") represent us and our successors and assigns, founders, partners, owners, directors, officers, employees. You / your / user / customer / purchaser / end user represent the person or the entity that uses this Application / Website whether or not you access the SERVICE available on the Application / Website or surf / browse / transaction on the Application / Website. Any person who accesses this SERVICE is presumed to be legally capable of entering into a legal contract and has understood and voluntarily accepted the said Terms of Services.</p><br>
    <p id="justify">These Terms of Service govern your use of our website www.Eatsapp.in, www.wolotech.com and our “Eatsapp” application for Mobile and handheld devices (the “App”). The Website and the App are jointly referred to as the “SERVICE”).</p><br>
    <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules.</p><br>
    <p id="justify">It is required that you understand each part of these Terms of Service completely and only once you have understood them fully and are agreeing each and every part, you may use our SERVICE. In case if you do not agree with even a single point, you should not to use our SERVICE. It will be construed as acceptance of the said Terms of Services if you use or access our SERVICE.</p>
    <p id="justify">Only individuals who are 18 years of age or older may use the SERVICE. If you are under 18 years of age and you wish to download, install, access or use the SERVICE, your parents or legal guardian must acknowledge and agree to the Terms of Service and Privacy Policy. Should your parents or legal guardian fail to agree or acknowledge the Terms of Service and Privacy Policy, you shall not use our SERVICE and or immediately discontinue its use them immediately.</p>
    <p id="justify">You shall at all times be responsible for the use of the SERVICE through your mobile device and for bringing these Terms of Service and Privacy Policy to the attention of all such persons accessing the SERVICE on your computer or mobile device.</p>
    <p id="justify">You understand and agree that the use of the SERVICE does not include the provision of a mobile device or other necessary equipment to access it. You also understand and acknowledge that the use of the SERVICE requires internet connectivity and telecommunication links. You shall bear the costs incurred to access and use the SERVICE and we shall not, under any circumstances whatsoever, be responsible or liable for such costs.</p>
    <p id="justify">You agree to receive promotional Calls, Emails, SMSs, MMSs and or Notifications from Eatsapp or allied partners.</p>
    <p id="justify">By installing, downloading or using the SERVICE, you signify your acceptance to the Terms of Service and Privacy Policy which takes effect on the date on which you download, install or use the Services, and create a legally binding arrangement to abide by the same.</p>
    <p id="justify">These Terms contains the entire understanding and agreement between you and us and it supersedes any and all prior understandings. We will be updating our Terms of Service from time to time and it is absolutely your responsibility to keep checking such updates. Your using our SERVICE will mean that you have read and understood the latest updated Terms of Service and you are in fully agreement with it. We are not responsible for informing you about informing you about such updates. </p>
    <p id="justify"><b>Account Control:</b> You can create your account and access the service by using your mobile number only. You will need active SMS connection on that mobile device. We solely reserve the right to accept or reject application made by User for having the User Account without obligation of any explanation. We reserve the right to store, evaluate, analyse, verify and authenticate the personal information and data provided directly or indirectly by the User. We reserve the right to suspend or withdraw access to the SERVICE to you personally, or to some or to all users temporarily or permanently at any time without notice for any reasons whatsoever and without obligation of any explanation. </p>
    <p id="justify"><b>Code of conduct:</b> The SERVICE shall facilitate the User to order Food online by using the Eatsapp App. You acknowledge, agree that you have complete responsibility while ordering Food through the Eatsapp App. The User’s discretion is required while using the SERVICE. The SERVICE shall be used solely for User’s non-exclusive, non-assignable, non-transferable and limited personal use and for no other purposes. User’s use of the SERVICE is subject to all applicable local, state, national laws and regulations. User shall not in any manner do or attempt to copy, change, alter, amend, reverse engineer, decompile, reverse translate, disassemble, publish, disclose, display or make available, or in any other manner, decode the Eatsapp App and / or the Website.</p> 
    <p id="justify">You shall not host, display, upload, modify, publish, transmit, update or share or attempt to host, display, upload, modify, publish, transmit, update or share any information that contains restricted or password-only access pages, or hidden pages or images. </p>
    <p id="justify">You shall not host, display, upload, modify, publish, transmit, update or share or attempt to host, display, upload, modify, publish, transmit, update or share any information that violates any law for the time being in force.</p> 
    <p id="justify">You shall not use any “virus”, "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual / software process / program intended to harm or destroy any information, software / hardware / systems etc and / or access, acquire, copy or monitor any portion of our content, or in any way reproduce or circumvent the navigational structure or presentation of Eatsapp or any of its content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available by us.</p>
    <p id="justify">We reserve the right to bar any such activity. You shall not probe, scan or test the vulnerability of Eatsapp App / Website nor breach the security or authentication measures on it or any network, and also shall not reverse look-up or seek to reverse look-up, trace or seek to trace any information of or visitor connected to it. </p>
    <p id="justify">You agree that you will not take any action that imposes an unreasonable or disproportionately large load on our infrastructure or any systems or networks connected to it.</p> 
    <p id="justify">You may not pretend that you are, or that you represent someone else, or impersonate any other individual or entity. </p>
    <p id="justify"><b>Trademarks, Copyrights and Proprietary Rights:</b> We are the sole and exclusive copyright owners of the Services and our Content. We also exclusively own the copyrights, trademarks, service marks, logos, trade names, trade dress and other intellectual and proprietary rights throughout the world (the “IP Rights”) associated with the Services and Eatsapp Content, which may be protected by copyright, patent, trademark and other applicable intellectual property and proprietary rights and laws. You acknowledge that the Services contain original works and have been developed, compiled, prepared, revised, selected, and arranged by us and others through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and constitutes valuable intellectual property of us and such others. You further acknowledge that the Services may contain information which is designated as confidential by WOLOTECH and that you shall not disclose such information without WOLOTECH’s prior written consent.</p>
    <p id="justify">You agree to protect WOLOTECH’s proprietary rights and the proprietary rights of all others having rights in the Services during and after the term of this agreement and to comply with all reasonable written requests made by us or our suppliers and licensors of content or otherwise to protect their and others’ contractual, statutory, and common law rights in the Services. You acknowledge and agree that WOLOTECH (or WOLOTECH’S licensors) own all legal right, title and interest in and to the Services, including any IP Rights which subsist in the Services (whether those rights happen to be registered or not, and wherever in the world those rights may exist). You agree not to use any framing techniques to enclose any trademark or logo or other proprietary information of WOLOTECH; or remove, conceal or obliterate any copyright or other proprietary notice or source identifier, including without limitation, the size, color, location or style of any proprietary mark(s). Any infringement shall lead to appropriate legal proceedings against you at appropriate forum for seeking all available/possible remedies under applicable laws of the country of violation. You cannot modify, reproduce, publicly display or exploit in any form or manner whatsoever any of the WOLOTECH’S Content in whole or in part except as expressly authorized by WOLOTECH.</p>
    <p id="justify"><b>Placing the Orders and Financial Terms:</b> You agree that Food purchased from Eatsapp is intended for your personal use and you represent that the same are not for resale or you are not acting as an agent for other parties. The SERVICE allows you to order food subject to the Terms stated in this document but not limited to availability and delivery location. Once order is placed and payment is made, it cannot be cancelled and the order will be treated as confirmed.</p>
    <p id="justify">All prices listed on the App for Food is correct at the time of publication. We reserve the right to alter the menu of Food available for sale on the App and to add, delete and remove from listing its menu of Food, Food Outlets and Food Delivery options. The details of the menu and price list available on the SERVICE are based on the information provided by the Vendors.</p>
    <p id="justify">The total price for Food and Food Delivery including all other charges, taxes, costs, if any, will be displayed on the Eatsapp App when you place your order. Full payment must be made for successful placement of the order. Payment has to be made by online using the payment options available.</p>
    <p id="justify">You acknowledge and agree that we act as the Vendor’s payment agent for the limited purpose of accepting payments from you on behalf of the Vendor and upon your successful payment to us your payment obligation is completed. You shall not, under any circumstances whatsoever, make any payment directly to the Vendor.</p>
    <p id="justify">Please note that we cannot control any amount that may be charged to you by your Bank / Credit Card Company / or any of your payment service providers related to your payment to us and we disclaim all liability in this regard.</p>
    <p id="justify">In connection with your order, we will be using the name as provided by you while creating the account or as per latest edited name by you. Also, your primary address will be adopted for the billing purpose.</p> 
    <p id="justify">We will be emailing you the bill on the email address provided by you in your profile. If there is no email address provided, we will request you to provide one in ordering process, which will be optional. If no email address is provided, we will not ba able to email the Bill to you. We will never send the physical bill to your registered or to any addresses. If you want to get the Bill, you will have to provide the correct and working email address. </p>
    <p id="justify">For online payment, you shall ensure that online payment mode is secure. Your payment details will be encrypted to prevent the possibility of someone being able to read them as they are sent over the internet. Your credit card company may also conduct necessary security checks to confirm about your identification before making any such payment. You understand, acknowledge and agree that although we provide appropriate protection, the Internet and hence our Service is not hack proof. Data pilferage due to unauthorized hacking, virus attacks, technical issues is possible and we are not responsible for any outcomes of such event(s). If we receive any orders, or any sort of communication, requests, from your mobile number or your email address, we will consider that it is you who have communicated and we will have no reason to think otherwise. We do not provide any security for opening the application. You are required to keep your mobile device and your email access secure.</p>
    <p id="justify"><b>Delivery:</b> The food will be delivered either by our own delivery boys or using third party delivery partners or may be by the food outlets themselves or using their delivery partners.</p>
    <p id="justify">Delivery period quoted at the time of ordering are approximate only and may vary. Food will be delivered to the place as selected or marked or intimated by you while ordering.</p>
    <p id="justify">If delivery is done by the food outlets or its delivery partners, it is their sole responsibility to provide food delivery in a timely manner. In case delivery is done by us or our third party delivery partners, we will take reasonable care to deliver in a timely manner. No responsibility is taken for late delivery by us in either case. And we will not be liable for any loss caused to you by late delivery. If the Food is not delivered within the estimated delivery time quoted, you shall contact the delivery boy by clicking on the call button provided in page meant for tracking the order. In case of a late delivery, the delivery charge will neither be voided nor refunded by us. All risk in the Food and Food Delivery shall pass to you upon delivery.</p>
    <p id="justify">If you fail to accept delivery of Food at the time it is ready for delivery or if we are unable to deliver at the nominated time due to your failure to provide appropriate instructions, proper address or required authorizations, then the food shall be deemed to have been delivered to you and all risk and responsibility in relation to such food shall pass to you. Any storage, insurance and other costs which we incur as a result of the inability to deliver shall be your responsibility and you shall indemnify us in full for such cost.</p>
    <p id="justify">You must ensure that at the time of delivery of Food adequate arrangements, including access where necessary, are in place for the safe delivery of the Food. We cannot be held liable for any damage, cost or expense incurred to such Food as a result of a failure to provide adequate access or arrangements for delivery. You shall keep in contact with the Delivery Boy and make all arrangements for him to access the delivery location. We shall not be liable to you for any losses, liabilities, costs, damages, charges or expenses arising out of late delivery. Our decision in relation to this shall be final and binding.</p>
    <p id="justify">Your order will be only delivered to the address / pitstop / selected location designated by you at the time of placing the order on the SERVICE. We reserve the right to cancel the order, in our sole discretion, in the event of any change to the place of delivery and you shall not be entitled to any refund for the same. Delivery in the event of change of the delivery location shall be at our sole discretion. For orders to be picked up from the food outlet, you will be required to arrive at the food outlet in time. If you fail to reach within reasonable time, the food outlet may destroy the food and your order will be deemed to have been delivered. Our decision in relation to this shall be final and binding.</p>
    <p id="justify">For deliveries to be done in cars, you will have to wait at the pitstop until the food is delivered. Any objections, charges, penalty or proceedings forced upon you by the RTO / Police / Governmental Organization / Non-Governmental Organization or any other entity is your responsibility and liability alone and is to be dealt by you alone and all liabilities including the legal expenses to be absorbed by you alone and you indemnify us from for the above said objections, charges, penalty or proceedings forced upon you by the RTO / Police / Governmental Organization / Non-Governmental Organization or any other entity including the legal or other direct or indirect associated expenses.</p>
    <p id="justify">We believe in keeping India clean. You are required not to litter anywhere including but not limited to delivery locations, public places or roads where you consume the food. If you litter, you shall do that at your own risk and responsibility. Any objections, charges, penalty or proceedings forced upon you by the RTO / Police / Governmental Organization / Non-Governmental Organization or any other entity is your responsibility and liability alone and is to be dealt by you alone and all liabilities including the legal expenses to be absorbed by you alone and you indemnify us from for the above said objections, charges, penalty or proceedings forced upon you by the RTO / Police / Governmental Organization / Non-Governmental Organization or any other entity including the legal or other direct or indirect associated expenses.</p> 
    <p id="justify">Order Cancellations and Refunds: Once order is successfully placed, it cannot be cancelled.</p>
    <p id="justify">However, in the unlikely event of an item or items on your order being unavailable, we will intimate you by sending the Notification of such unavailability and cancel the entire order and refund the entire payment amount.</p>
    <p>We reserve the sole right to cancel your order in the following circumstance:</p>
    <ul>
      <li>in the event of the designated address following outside the delivery zone offered by us;</li>
      <li>failure to deliver your order due to lack of information, direction or authorization from you at the time of delivery;</li>
      <li>unavailability of all the items ordered by you at the time of booking the order;</li>
      <li>failure due to reasons beyond our control or attributable to the Vendor.</li>
    </ul>
    <p>You shall be entitled to a refund only if:</p>
    <ul>
     <li>your order packaging has been tampered or damaged at the time of delivery;</li>
     <li>us cancelling your order due to your delivery location following outside our designated delivery zones.</li>
    </ul>
    <p>Our decision on refunds shall be at our sole discretion and shall be final and binding.</p>
    <p>All refund amounts shall be credited to your account within 15 business days.</p>
    <p id="justify"><b>Payment:</b> We accept only digital payment. As of now we do not accept Cash on Delivery Option as a payment. To carry out the successful transaction, we will require your Personal Information (type 2) as described in Privacy Policy. This information includes but is not limited to all personal information such as billing information, credit card, debit card, e-Wallets details, Bank Details, Bank Account Details, UPI Details and any other payment instrument, etc…</p>
    <p id="justify">We will be required to provide Personal Information (type 2) to the approved payment gateways while making the payment. In this regard you agree to provide correct and accurate details to the approved payment gateways for availing the SERVICE. These Payment Gateways or Payment Service Providers are our Third Party Partners. You shall not use the payment credentials which are not lawfully owned by you, i.e. in any transaction, you must use your own payment credentials like credit card, debit card, payment wallets etc… You will be solely responsible for the security and confidentiality of your payment credentials. We expressly disclaim all liabilities that may arise as a consequence of any unauthorized use of your payment credentials. As stated earlier, you understand, acknowledge and agree that although we provide appropriate protection, the Internet and hence our Service is not hack proof. Data pilferage due to unauthorized hacking, virus attacks, technical issues is possible and we are not responsible for any outcomes of such event(s). If we receive any orders, or any sort of communication, requests, from your mobile number or your email address, we will consider that it is you who have communicated and we will have no reason to think otherwise. We do not provide any security for opening the application. You are required to keep your mobile device and your email access secure.</p>
    <p><b>By using the Service you agree, represent, understand, agree and warrant that:</b></p>
    <ol>
      <li>you are giving the exact and accurate information about your identity, but we do not attempt to confirm and we do not confirm your purported identity.</li>
      <li>Our SERVICE will be provided during the working hours of the relevant Third party partners.</li>
      <li>Neither us nor any of our Third Party Partners shall be liable in the event of you failing to adhere to these Terms of Service.</li>
      <li>Any legal remedy or liability that you seek to obtain for action or omission of other members or other Third Parties will be limited to a claim against that Third Party who have caused you harm and you agree not to attempt to impose liability on, or seek any legal remedy from us with respect to such actions or omissions.</li>
      <li>You are using our SERVICE at your own risk.</li>
      <li>Our liability ends once you order has been delivered to you.</li>
      <li>Your use of the SERVICE shall be solely for your personal use and you shall not authorize others to use your account, including your profile or email address and that you are solely responsible for all content published or displayed through your account, including any email messages, and you shall abide by all applicable local, state, national and foreign laws, treaties and regulations, including those related to data privacy, international communications and the transmission of technical or personal data.</li>
      <li>You will not use our SERVICE for commercial purposes of any kind.
</li>
      <li>You will not use the SERVICE in any way that is unlawful, or harms us or any other person or entity, as determined in our sole discretion. </li>
      <li>You will not use another person’s credential or information or identity or other account information, or another person’s name, image or photograph or impersonate any person or entity or misrepresent your identity or affiliation with any person or entity.</li>
      <li>We try to make our service available during the working hours, but we do not assure or guarantee that the services will be uninterrupted, error-free, timely, free of viruses or other harmful components or that such defects if any will be corrected.</li>
      <li>The Food Outlets you choose to order from our App will be responsible for quality of food provided to you. We insist but in no way we can ensure that they provide food that is compliant with Food Safety & Standard Act, Package & Label Act and Weight and Measures Act.</li>
      <li>We do not warrant that the SERVICE will be compatible with all hardware and software which you may use. We shall not be liable for damage to, or viruses or other code that may affect, any equipment (including but not limited to your mobile device, computer), software, data or other property as a result of your download, installation, access to or use of the SERVICE or your obtaining any material from, or as a result of using, the SERVICE. We shall also not be liable for the actions of Third Parties.</li>
      <li>We do not represent or warranty that the information available on the SERVICE will be correct, accurate or otherwise reliable.</li>
      <li>In the event the SERVICE is accessed on a mobile device, it is not associated, affiliated, sponsored, endorsed or in any way linked to any platform operator, including, without limitation, Apple, Google, Android, Nokia, RIM Blackberry or to companies like Vodafone, Airtel, Jio, Idea, etc… (each being an “Operator”).</li>
      <li>Your download, installation, access to or use of the SERVICE is also bound by the terms and conditions of the Operator.</li>
      <li>You and we acknowledge that these Terms of Service are concluded between you and us only, and not with any Operator. You further acknowledge that we, are solely responsible for the SERVICE and the content thereof to the extent specified in these Terms of Use. These Operators have rights nor are they responsible in providing this SERVICE.</li>
      <li>The license granted to you for use of the SERVICE is limited and is non-transferable license to use the SERVICE on a mobile device or computer that you own or control.</li>
      <li>We are solely responsible for providing any maintenance and support services with respect to the SERVICE as required under applicable law. You acknowledge that an Operator has no obligation whatsoever to furnish any maintenance and support services with respect to the SERVICE.</li>
      <li>You and we acknowledge that only we and not the relevant Operator, are responsible for addressing any claims relating to the SERVICE or your possession and / or use of the SERVICE, including, but not limited to: (i) any claim that the SERVICE fails to conform to any applicable legal or regulatory requirement; and (ii) claims arising under consumer protection or similar legislation.</li>
      <li>You must comply with any applicable Other Party terms of agreement when using the Services (e.g. you must ensure that your use of the Services is not in violation of your mobile device agreement or any wireless data service agreement).</li>
      <li>You and we acknowledge and agree that the relevant Operator, and that Operator’s subsidiaries, are Other Party beneficiaries of these Terms of Service, and that, upon your acceptance of these Terms of Service, that Other Party will have the right (and will be deemed to have accepted the right) to enforce these Terms of Service against you.</li>
      <li>You authorize us to use, store or otherwise process your Personal Information (type 1) and Personal Information (type 2) to provide our SERVICE and for marketing and credit control purposes which may include the disclosure of your personal information to selected parties from time to time where we believe that the services offered by such parties may be of interest to you or where this is required by law or in order to provide the our SERVICE to you in currently or in future. More information can be found in Privacy Policy.</li>
      <li>You authorize Eatsapp to track you location anytime and share it with Third Party.</li>
      <li>We cannot and will not assure that other users are or will be complying with the rules or any other provisions of this Terms of Service, and, as between you and us, you hereby assume all risk of harm or injury resulting from any such lack of compliance by yourself or them. </li>
      <li>You acknowledge that when you access a link that leaves the Services, the site you will enter into is not controlled by us and may have different terms of service and privacy policy. By going to other sites, you acknowledge that we are not responsible for those sites. We reserve the right to disable links to and / or from other sites to our Services, although we are under no obligation to do so.</li>
      <li>Your and our relationship is only that of service user and service provider. You are in no way our legal representative, partner or agent for any reason.</li>
      <li>You will not assign or transfer or delegate or purport to assign or transfer or delegate the agreement between you and us.</li>
      <li>You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the our SERVICE or any transaction being conducted.</li>
      <li>You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about us or the brand name or domain name used by us, or otherwise engage in any conduct or action that might tarnish our or our vendor’s image or reputation, on any platform or otherwise tarnish or dilute any of our trade or service marks, trade name and / or goodwill associated with such trade or service marks, trade name as may be owned or used by us.</li>
      <li>We shall have all the rights to take necessary action and claim damages that may occur due to your involvement / participation in any way on your own or through groups of people, intentionally or unintentionally in not following the Terms of Service.</li>
    </ol>
    <ol>
      <li>we are the owner or the licensee of all intellectual property rights in the Services, and in the material published on it. Those works are protected by copyright laws and treaties around the world. All such rights are reserved.</li>
      <li>you may print off one copy, and may download extracts, of any page(s) from the SERVICE only for your personal reference.</li>
      <li>you must not modify the paper or digital copies of any materials you have printed off or downloaded in any way, and you must not use any illustrations, photographs, video or audio sequences or any graphics separately from any accompanying text.</li>
      <li>you must not use any part of the materials on the SERVICE for commercial purposes without obtaining a licence to do so from us or our licensors.</li>
      <li>If you print off, copy or download any part of the Services in breach of these Terms of Service, your right to use the SERVICE will cease immediately and you must, at our option, return or destroy any copies of the materials you have made.</li>
      <li><b>Waiver:</b> Our failure to enforce or to exercise at any time or for any period any term of or any right pursuant to these Terms shall not be construed as the waiver of any such right and shall in no way affect our right later to enforce or exercise it.</li>
      <li><b>Severability:</b> If any part of the Terms is found or determined to be void and unenforceable by any applicable laws, that particular part or portion shall be edited or deleted, but it will not affect the validity of the remaining provisions of Terms, which shall remain valid and enforceable.</li>
      <li><b>Information provided by you:</b> We collect various types of information from you either directly or indirectly. We process information about you in accordance with our Privacy Policy. You hereby grant to us an irrevocable, royalty-free, worldwide, assignable, sub-licensable licence to use any material which you submit to us on the SERVICE for the purpose of use on the SERVICE or for our generally marketing (by any means and in any media, including, but not limited to, on our website or in our journals) our SERVICE. You agree that you waive your moral rights to be identified as the author and we may modify your submission. In case we are required to respond to or required to disclose your personal information in order to assist the Government Authority or in adherence to the Court Order or other legal process or to protect the interest of our SERVICE and / or any particular user(s), we will disclose it without obtaining permission from you. You authorize us to disclose your personal information. This may include Personal Information (type 1) and also Personal Information (type 2).</li>
      <li><b>Disclaimers:</b> We hereby formally state that we are not legally responsible for following:</li>
    </ol> 
    <p>THE SERVICES MAY BE UNDER CONSTANT UPGRADES, AND SOME FUNCTIONS AND FEATURES MAY NOT BE FULLY OPERATIONAL.</p>
    <p id="justify">DUE TO THE VAGARIES THAT CAN OCCUR IN THE ELECTRONIC DISTRIBUTION OF INFORMATION AND DUE TO THE LIMITATIONS INHERENT IN PROVIDING INFORMATION OBTAINED FROM MULTIPLE SOURCES, THERE MAY BE DELAYS, OMISSIONS, OR INACCURACIES IN THE CONTENT PROVIDED ON THE SERVICE OR DELAY OR ERRORS IN FUNCTIONALITY OF THE SERVICE. AS A RESULT, WE DO NOT REPRESENT THAT THE INFORMATION POSTED IS TRUE OR CORRECT.</p>
    <p id="justify">WE EXPRESSLY DISCLAIM ALL LIABILITIES THAT MAY ARISE AS A CONSEQUENCE OF ANY UNAUTHORIZED USE OF YOUR PAYMENT CREDENTIAL AND INFORMATION.</p>
    <p id="justify">YOU ACKNOWLEDGE THAT THIRD PARTY SERVICES ARE AVAILABLE ON THE SERVICES. WE MAY HAVE FORMED PARTNERSHIPS OR ALLIANCES WITH SOME OF THESE THIRD PARTIES FROM TIME TO TIME IN ORDER TO FACILITATE THE PROVISION OF CERTAIN SERVICES TO YOU. HOWEVER, YOU ACKNOWLEDGE AND AGREE THAT AT NO TIME ARE WE MAKING ANY REPRESENTATION OR WARRANTY REGARDING ANY THIRD PARTY’S SERVICES NOR WILL WE BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY CONSEQUENCES OR CLAIMS ARISING FROM OR IN CONNECTION WITH SUCH THIRD PARTY INCLUDING, AND NOT LIMITED TO, ANY LIABILITY OR RESPONSIBILITY FOR, DEATH, INJURY OR IMPAIRMENT EXPERIENCED BY YOU OR ANY THIRD PARTY. YOU HEREBY DISCLAIM AND WAIVE ANY RIGHTS AND CLAIMS YOU MAY HAVE AGAINST US WITH RESPECT TO THIRD PARTY’S / VENDORS SERVICES.</p>
    <p id="justify">WHILE THE MATERIALS PROVIDED ON THE SERVICES WERE PREPARED TO PROVIDE ACCURATE INFORMATION REGARDING THE SUBJECT DISCUSSED, THE INFORMATION CONTAINED IN THESE MATERIALS IS BEING MADE AVAILABLE WITH THE UNDERSTANDING THAT WE MAKE NO GUARANTEES, REPRESENTATIONS OR WARRANTIES WHATSOEVER, WHETHER EXPRESSED OR IMPLIED, WITH RESPECT TO PROFESSIONAL QUALIFICATIONS, EXPERTISE, QUALITY OF WORK OR OTHER INFORMATION HEREIN. IN NO EVENT SHALL WE BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DECISION MADE OR ACTION TAKEN IN RELIANCE ON SUCH INFORMATION.</p>
    <p id="justify">THE INFORMATION PROVIDED HEREUNDER IS PROVIDED “AS IS”. WE MAKE NO WARRANTY OR REPRESENTATION REGARDING THE TIMELINESS, CONTENT, SEQUENCE, ACCURACY, EFFECTIVENESS OR COMPLETENESS OF ANY INFORMATION OR DATA FURNISHED HEREUNDER OR THAT THE INFORMATION OR DATA PROVIDED HEREUNDER MAY BE RELIED UPON. MULTIPLE RESPONSES MAY USUALLY BE MADE AVAILABLE FROM DIFFERENT SOURCES AND IT IS LEFT TO THE JUDGEMENT OF USERS BASED ON THEIR SPECIFIC CIRCUMSTANCES TO USE, ADAPT, MODIFY OR ALTER SUGGESTIONS OR USE THEM IN CONJUNCTION WITH ANY OTHER SOURCES THEY MAY HAVE, THEREBY ABSOLVING US AS WELL AS OUR CONSULTANTS, BUSINESS ASSOCIATES, AFFILIATES, BUSINESS PARTNERS AND EMPLOYEES FROM ANY KIND OF PROFESSIONAL LIABILITY.</p>
    <p id="justify">WE SHALL NOT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY LOSSES OR INJURY ARISING OUT OF OR RELATING TO THE INFORMATION PROVIDED ON THE SERVICE. IN NO EVENT WILL WE OR OUR EMPLOYEES, AFFILIATES, AUTHORS OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DECISION MADE OR ACTION TAKEN BY YOUR RELIANCE ON THE CONTENT CONTAINED HEREIN.</p>
    <p id="justify">IN NO EVENT WILL WE BE LIABLE FOR ANY DAMAGES (INCLUDING, WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, DAMAGES ARISING FROM PERSONAL INJURY/ WRONGFUL DEATH, AND DAMAGES RESULTING FROM LOST PROFITS, LOST DATA OR BUSINESS INTERRUPTION), RESULTING FROM ANY SERVICES PROVIDED BY ANY THIRD PARTY OR VENDOR ACCESSED THROUGH THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY AND WHETHER OR NOT WE ARE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
    <p id="justify">YOU UNDERSTAND AND AGREE THAT, TO THE FULLEST EXTENT PERMISSIBLE BY LAW, WE AND OUR SUCCESSORS AND ASSIGNS, OR ANY OF THEIR AFFILIATES OR THEIR RESPECTIVE OFFICERS, FOUNDERS, OWNERS, PARTNERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, REPRESENTATIVES, OPERATIONAL SERVICE PROVIDERS, ADVERTISERS OR SUPPLIERS WILL NOT BE RESPONSIBLE FOR YOUR OR ANY USER’S PERSONAL INJURY/ ILLNESS / HEALTH EFFECTS / WRONGFUL DEATH OCCURING DUE TO USE OF THE SERVICE.</p>
    <p id="justify">THE SERVICE AND ALL CONTENTS, MATERIALS AND POSTINGS ARE MADE AVAILABLE ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY REPRESENTATION OR WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. YOUR DATA MAY GET PILFERED, DAMAGED, LOST, GARBLED OR BECOME USELESS. WITHOUT LIMITING THE FOREGOING, WE ARE NOT RESPONSIBLE OR LIABLE FOR ANY MALICIOUS CODE, DELAYS, INACCURACIES, ERRORS, OR OMISSIONS ARISING OUT OF YOUR USE OF THE SERVICE. YOU UNDERSTAND, ACKNOWLEDGE AND AGREE THAT YOU ARE ASSUMING THE ENTIRE RISK AS TO YOUR DATA, QUALITY, ACCURACY, PERFORMANCE, TIMELINESS, ADEQUACY, COMPLETENESS, CORRECTNESS, AUTHENTICITY, SAFETY, SECURITY AND VALIDITY OF ANY AND ALL FEATURES AND FUNCTIONS OF THE SERVICE, INCLUDING, WITHOUT LIMITATION, POSTINGS AND MATERIALS ASSOCIATED WITH YOUR USE OF THE SERVICE.</p>
    <p id="justify">YOU UNDERSTAND AND AGREE THAT, TO THE FULLEST EXTENT PERMISSIBLE BY LAW, WE AND OUR SUCCESSORS AND ASSIGNS, OR ANY OF THEIR AFFILIATES OR THEIR RESPECTIVE OFFICERS, FOUNDERS, OWNERS, PARTNERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, REPRESENTATIVES, OPERATIONAL SERVICE PROVIDERS, ADVERTISERS OR SUPPLIERS SHALL NOT BE LIABLE FOR ANY LOSS OR DAMAGE, OF ANY KIND, DIRECT OR INDIRECT, IN CONNECTION WITH OR ARISING FROM USE OF THE SERVICE OR FROM THIS TERMS OF USE, INCLUDING, BUT NOT LIMITED TO, COMPENSATORY, CONSEQUENTIAL, INCIDENTAL, INDIRECT, SPECIAL OR PUNITIVE DAMAGES.</p>
    <p id="justify">UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER IN TORT, CONTRACT, OR OTHERWISE, SHALL WE BE LIABLE TO YOU OR TO ANY OTHER PERSON OR ENTITY FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF GOODWILL, LOSS OF CONFIDENTIAL OR OTHER INFORMATION, BUSINESS INTERRUPTION, WORK STOPPAGE, MOBILE AND OR COMPUTER FAILURE OR MALFUNCTION, PERSONAL INJURY, HEALTH, LOSS OF PRIVACY, FAILURE TO MEET ANY DUTY INCLUDING A DUTY OF GOOD FAITH OR OF REASONABLE CARE, NEGLIGENCE (WHETHER ACTIVE OR PASSIVE), AND ANY OTHER PECUNIARY OR OTHER LOSS WHATSOEVER) ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OR INABILITY TO USE THE SERVICE, LOSS OF DATA OR OTHERWISE UNDER OR IN CONNECTION WITH ANY PROVISION OF THESE TERMS, EVEN IN THE EVENT OF FAULT, TORT (INCLUDING NEGLIGENCE AND GROSS NEGLIGENCE), STRICT LIABILITY, BREACH OF CONTRACT, OR BREACH OF WARRANTY, AND EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL WE BE LIABLE FOR ANY DAMAGES IN EXCESS OF YOUR LAST ORDER PLACED ON EATSAPP APP IF ANY.</p>
    <p id="justify">It is possible that other users (including unauthorized users or "hackers") may do such acts that You may be involuntarily exposed to offensive and obscene materials. It also is possible for others to obtain personal information about You due to your use of the SERVICE, and that the recipient may use such information to harass or injure You OR USE IT IN UNLAWFUL MANNER. We do not approve of such unauthorized uses, but by using the SERVICE You acknowledge and agree that We are not IN ANY MANNER responsible for ANY OUTCOME THANT MAY ARISE DUE TO THE ABOVE AND WE WILL NOT BE HELD RESPONSIBLE OR LIABLE UNDER ANYCIRCUMSTANCES.</p>
    <p id="justify">Photographs provided on the Eatsapp App and / or Website are only for reference and shall be treated as an example without any warranty, guarantee, quality, suitability, look, taste and feel. The Food items displayed in photographs or advertisements may have variations in colours, tastes, looks, feel, packaging etc. when compared to the delivered Food items.</p>
    <p id="justify"><b>INDEMNIFICATION:</b> You agree and confirm to indemnify, defend and hold us, our parents, subsidiaries, affiliates, successors, assigns and licensors, franchisees or sub-franchisees, any of our respective officers, founders, owners, partners, directors, employees, agents, vendors, licensors, representatives, advertisers, service providers and suppliers harmless from and against any and all claims, actions, losses, expenses, damages and costs (including reasonable attorneys' fees), resulting from any breach or violation of Terms, or due to your activities related to the SERVICE, whether by use of your account or otherwise or due to Events beyond our control.</p>
    <p id="justify"><b>Legal:</b> Terms and your use of our Service is governed by, construed and enforced in accordance with the laws of India applicable to contracts made, executed and wholly performed on the our Service, and, for the purposes of any and all legal or equitable actions the you and us shall be referred to arbitration in accordance with the provisions of the arbitration law in city of Mumbai only. And if for any reason whatsoever, arbitration judgment is not satisfactory either you or us agree and submit to the exclusive jurisdiction and venue of the Courts of Mumbai only and you will not object to such jurisdiction or venue.</p>
    <p id="justify"><b>Events beyond our control:</b> Without limitation, under no circumstances shall we shall be held liable for any damage or loss due to our deficiency in performance resulting directly or indirectly from acts of nature, forces or causes beyond control, including without limitation, Internet failures, computer equipment failures, mobile equipment failures, Servers problems, telecommunication equipment failures, other equipment failures, electrical power fluctuations or failures, third party service providers failures, GPS connectivity issues, comparatively cloud cover, rains, heavy traffic, enforcement by RTO or police, road works, change of Government rules and regulations, change of Non-Governmental rules and regulations, Change of Terms or Privacy Policies of Third Party Partners or others that directly or indirectly affect our Services.</p>
    <p id="justify"><b>Queries:</b> In case of any queries, please write to Wolotech LLP on registers address (Wolotech LLP, 152, 15th Floor, Mittal Court (B), Nariman Point, Mumbai 400021) or send an email on contact@wolotech.com with subject “Grievance – Mobile Number”.</p>
</div>
</div>

<?php include 'footer.php'; ?>